// <auto-generated />
namespace Venta_Vehiculos_2014067.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class db_vehiculo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_vehiculo));
        
        string IMigrationMetadata.Id
        {
            get { return "201604151615123_db_vehiculo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
